name: muon-ssh
version: "3.1.0-beta"
summary: Your All-in-One SSH Solution
description: |
  Muon redefines the way you connect to remote servers. As a sleek, graphical SSH client, it combines essential tools into one intuitive interface. Browse files, manage resources, analyze disk space, and edit text seamlessly—all while running commands in its built-in terminal emulator. With added features like a log viewer and process manager, Muon streamlines your workflow, making server management simpler and more efficient. Elevate your remote work experience with Muon: where power meets simplicity.

  More information is available on GitHub Repo: https://github.com/devlinx9/muon-ssh
title: MuonSSH
website: https://github.com/devlinx9/muon-ssh
issues: https://github.com/devlinx9/muon-ssh/issues
grade: devel # Change to "stable" for release
base: core22
icon: snap/gui/muonssh.png
confinement: classic

compression: lzo

apps:
  muon-ssh:
    command: usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar $SNAP/jar/muonssh_3.0.0.jar
    common-id: muonssh.desktop
    environment:
      # Needed for fontconfig
      XDG_DATA_HOME: ${SNAP}/usr/share
      FONTCONFIG_PATH: ${SNAP}/etc/fonts/config.d
      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
      JAVA_HOME: ${SNAP}/usr/lib/jvm/java-17-openjdk-amd64
      PATH: ${SNAP}/usr/bin:${JAVA_HOME}/bin:$PATH

parts:
  muon-ssh:
    plugin: dump
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/jar/
      snapcraftctl build
      cp muon-app/target/muonssh*.jar $SNAPCRAFT_PART_INSTALL/jar/
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-17-jre-headless
    stage-packages:
      - openjdk-17-jre
      - openjdk-17-jre-headless
      - x11-utils
    override-prime: |
      snapcraftctl prime
      # Ensure no external symlink remains
      cp /etc/ssl/certs/java/cacerts usr/lib/jvm/java-17-openjdk-amd64/lib/security/cacerts